# Generated by Django 3.1.7 on 2021-03-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ФИО')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
            ],
        ),
    ]
