# Generated by Django 3.1.7 on 2021-03-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AddField(
            model_name='workers',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workers',
            name='education',
            field=models.CharField(choices=[('mid_ed', 'mid_ed'), ('no_ed', 'no_ed'), ('hight_ed', 'hight_ed')], default='no_ed', max_length=30),
        ),
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='position',
            field=models.CharField(choices=[('codder', 'codder'), ('manager', 'manager'), ('hight_spec', 'hight_spec'), ('low_spec', 'low_spec'), ('cleaner', 'cleaner'), ('owner', 'owner')], default='codder', max_length=20),
        ),
    ]
